version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/image-component"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99